### Hiberbee Theme
## Original Author: Vlad Volkov
# URL: https://github.com/hiberbee/themes
## Modified by honhimW
# URL: https://github.com/honhimW/hiberbee-themes

"attribute" = "purple"

## type
"type" = "blue"
"type.builtin" = "red"
"type.enum.variant" = "orange"

# "constructor" = ""

## constant
"constant" = "orange2"
"constant.builtin" = "red"
"constant.numeric" = "orange2"
"constant.character.escape" = "orange"

## string
"string" = "yellow"
"string.regexp" = "yellow"
#"string.special" = "yellow"

## comment
"comment" = "grey"
#"comment.line" = "grey"
#"comment.block" = "grey"

## variable
"variable" = "purple2"
"variable.builtin" = "purple2"
"variable.parameter" = "orange3"
"variable.other.member" = "red2"

## label
"label" = "blue2"

## punctuation
"punctuation" = "light1"
#"punctuation.delimiter" = "grey"
#"punctuation.bracket" = ""
#"punctuation.special" = ""

## keyword
"keyword" = "red"

## operator
"operator" = "blue"

## function
"function" = "green"
#"function.builtin" = "blue"
"function.macro" = "purple"


"tag" = "green"
"namespace" = "blue"
"module" = "blue"
"special" = "orange"

## markup
"markup.heading.marker" = "grey"
"markup.heading.1" = { fg = "red", modifiers = ["bold"] }
"markup.heading.2" = { fg = "orange", modifiers = ["bold"] }
"markup.heading.3" = { fg = "yellow", modifiers = ["bold"] }
"markup.heading.4" = { fg = "green", modifiers = ["bold"] }
"markup.heading.5" = { fg = "blue", modifiers = ["bold"] }
"markup.heading.6" = { fg = "light10", modifiers = ["bold"] }
"markup.list" = "red"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.link.url" = { fg = "blue", modifiers = ["underlined"] }
"markup.link.text" = "purple"
"markup.quote" = "grey"
"markup.raw" = "green"

## version control changes
"diff.plus" = "green"
"diff.delta" = "orange"
"diff.minus" = "red"

## ui
"ui.background" = { bg = "dark3" }
"ui.cursor" = { modifiers = ['reversed'] }
"ui.cursor.match" = { fg = "orange", bg = "diff_yellow" }
"ui.cursor.insert" = { fg = "dark0", bg = "dark6" }
"ui.cursor.select" = { fg = "dark1", bg = "blue" }
"ui.selection" = { bg = "dark4" }
"ui.linenr" = "light1"
"ui.linenr.selected" = "light7"
"ui.cursorline.primary" = { bg = "light3" }
"ui.statusline" = { fg = "light6", bg = "dark6" }
"ui.statusline.inactive" = { fg = "light10", bg = "dark6" }
"ui.popup" = { fg = "light3", bg = "dark6" }
"ui.window" = { fg = "light6", bg = "dark6" }
"ui.help" = { fg = "light6", bg = "dark6" }
"ui.text" = "light6"
"ui.text.focus" = { fg = "light3", bg = "dark1" }
"ui.menu" = { fg = "light7", bg = "dark6" }
"ui.menu.selected" = { fg = "dark1", bg = "yellow" }
"ui.virtual.whitespace" = { fg = "grey_dim" }
"ui.virtual.ruler" = { bg = "grey_dim" }

info = { fg = 'green', bg = 'dark6' }
hint = { fg = 'blue', bg = 'dark6', modifiers = ['bold'] }
warning = { fg = 'yellow', bg = 'dark6', modifiers = ['bold'] }
error = { fg = 'red', bg = 'dark6', modifiers = ['bold'] }
diagnostic = { modifiers = ['underlined'] }



[palette]

diff_yellow = "#4e432f"
grey_dim = "#595f6f"

"dark1" = "#070605"
"dark2" = "#121110"
"dark3" = "#171615"
"dark4" = "#222120"
"dark5" = "#272625"
"dark6" = "#323130"
"dark7" = "#373635"
"dark8" = "#424140"
"dark9" = "#474645"
"dark10" = "#525150"
"grey" = "#ccbfaf"
"accent" = "#ffb900"
"green" = "#92D923"
"greenDark" = "#3d521b"
"blueDark" = "#253047a0"
"blue" = "#409cff"
"blue2" = "#00b7c3"
"red" = "#ee7762"
"red2" = "#ed005c"
"redDark" = "#260b08a0"
"yellow" = "#ffb900"
"yellowLight" = "#f5d277"
"yellowDark" = "#4d2f19"
"light1" = "#6f6e6d"
"light2" = "#7f7e7d"
"light3" = "#8f8e8d"
"light4" = "#9f9e9d"
"light5" = "#afaead"
"light6" = "#bfbebd"
"light7" = "#cfcecd"
"light8" = "#dfdedd"
"light9" = "#efeeed"
"light10" = "#fffefd"
"purple" = "#9380ff"
"purple2" = "#c16a97"
"orange" = "#f59762"
"orange2" = "#f25022"
"orange3" = "#ee9b70"