### Hiberbee Theme
## Original Author: Vlad Volkov
# URL: https://github.com/hiberbee/themes
## Modified by honhimW
# URL: https://github.com/honhimW/hiberbee-themes

"type" = "blue"
"constant" = "purple"
"constant.numeric" = "purple"
"constant.character.escape" = "orange"
"string" = "yellow"
"comment" = "grey"
"variable" = "fg"
"variable.builtin" = "orange"
"variable.parameter" = "fg"
"variable.other.member" = "fg"
"label" = "orange"
"punctuation" = "grey"
"punctuation.delimiter" = "grey"
"punctuation.bracket" = "fg"
"keyword" = "red"
"operator" = "orange"
"function" = "green"
"function.builtin" = "blue"
"function.macro" = "purple"
"tag" = "yellow"
"namespace" = "blue"
"attribute" = "purple"
"constructor" = "blue"
"module" = "blue"
"special" = "orange"

"markup.heading.marker" = "grey"
"markup.heading.1" = { fg = "red", modifiers = ["bold"] }
"markup.heading.2" = { fg = "orange", modifiers = ["bold"] }
"markup.heading.3" = { fg = "yellow", modifiers = ["bold"] }
"markup.heading.4" = { fg = "green", modifiers = ["bold"] }
"markup.heading.5" = { fg = "blue", modifiers = ["bold"] }
"markup.heading.6" = { fg = "fg", modifiers = ["bold"] }
"markup.list" = "red"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.link.url" = { fg = "blue", modifiers = ["underlined"] }
"markup.link.text" = "purple"
"markup.quote" = "grey"
"markup.raw" = "green"

"diff.plus" = "green"
"diff.delta" = "orange"
"diff.minus" = "red"

"ui.background" = { bg = "bg0" }
"ui.cursor" = { modifiers = ['reversed'] }
"ui.cursor.match" = { fg = "orange", bg = "diff_yellow" }
"ui.cursor.insert" = { fg = "black", bg = "grey" }
"ui.cursor.select" = { fg = "bg0", bg = "blue" }
"ui.selection" = { bg = "bg4" }
"ui.linenr" = "grey"
"ui.linenr.selected" = "fg"
"ui.cursorline.primary" = { bg = "bg1" }
"ui.statusline" = { fg = "fg", bg = "bg3" }
"ui.statusline.inactive" = { fg = "grey", bg = "bg1" }
"ui.popup" = { fg = "grey", bg = "bg2" }
"ui.window" = { fg = "grey", bg = "bg0" }
"ui.help" = { fg = "fg", bg = "bg1" }
"ui.text" = "fg"
"ui.text.focus" = "green"
"ui.menu" = { fg = "fg", bg = "bg2" }
"ui.menu.selected" = { fg = "bg0", bg = "green" }
"ui.virtual.whitespace" = { fg = "grey_dim" }
"ui.virtual.ruler" = { bg = "grey_dim" }

info = { fg = 'green', bg = 'bg2' }
hint = { fg = 'blue', bg = 'bg2', modifiers = ['bold'] }
warning = { fg = 'yellow', bg = 'bg2', modifiers = ['bold'] }
error = { fg = 'red', bg = 'bg2', modifiers = ['bold'] }
diagnostic = { modifiers = ['underlined'] }



[palette]

black = "#181819"
bg0 = "#2c2e34"
bg1 = "#33353f"
bg2 = "#363944"
bg3 = "#3b3e48"
bg4 = "#545862"
bg_red = "#ff6077"
diff_red = "#55393d"
bg_green = "#a7df78"
diff_green = "#394634"
bg_blue = "#85d3f2"
diff_blue = "#354157"
diff_yellow = "#4e432f"
fg = "#e2e2e3"
red = "#fc5d7c"
orange = "#f39660"
yellow = "#e7c664"
green = "#9ed072"
cyan = "#8dd0b6" # added for compatibility with `edge` scheme
blue = "#76cce0"
purple = "#b39df3"
grey = "#7f8490"
grey_dim = "#595f6f"

"dark1" = "#070605"
"dark2" = "#121110"
"dark3" = "#171615"
"dark4" = "#222120"
"dark5" = "#272625"
"dark6" = "#323130"
"dark7" = "#373635"
"dark8" = "#424140"
"dark9" = "#474645"
"dark10" = "#525150"
"accent" = "#ffb900"
"green" = "#92D923"
"greenDark" = "#3d521b"
"blueDark" = "#253047a0"
"blue" = "#409cff"
"red" = "#e81123"
"redDark" = "#260b08a0"
"yellow" = "#ffb900"
"yellowLight" = "#f5d277"
"yellowDark" = "#4d2f19"
"light1" = "#6f6e6d"
"light2" = "#7f7e7d"
"light3" = "#8f8e8d"
"light4" = "#9f9e9d"
"light5" = "#afaead"
"light6" = "#bfbebd"
"light7" = "#cfcecd"
"light8" = "#dfdedd"
"light9" = "#efeeed"
"light10" = "#fffefd"
